# Generated by Django 3.1.3 on 2021-12-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='updated_at',
        ),
    ]
